### ISSUE TITLE
Design Greetings Demo Inteface

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/eos-local#11]
The sample website will consist on a feed of greetings and a text box to send your greeting. 

Let's design a simple and nice interface for it.

**Comment by murillojorge** [comment]
Something like this?

![eosgreetings-desktop-proto-02](https://user-images.githubusercontent.com/1179619/47534932-724a1b80-d876-11e8-9105-88f779b70622.png)

**Comment by gaboesquivel** [comment]
I love it!  Not wallets have identities and not all people use that, so may we can remove the real name.

**Comment by murillojorge** [comment]
Without real names it could look like this:

![eosgreetings-desktop-proto-03](https://user-images.githubusercontent.com/1179619/47681661-b2b7db00-db8f-11e8-8a2e-170429d1db98.png)

**Comment by gaboesquivel** [comment]
great! thanks. Let's implement this design #24
