### ISSUE TITLE
Project Logo

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/eos-local#23]

**Comment by murillojorge** [comment]
A simple logo concept for EOSLocal. Alluding to ::1  

![eoslocal-logo-dots-01](https://user-images.githubusercontent.com/1179619/47825368-1f210e80-dd37-11e8-9f74-d7710a6eb16d.png)

**Comment by gaboesquivel** [comment]
perfect, thanks!

**Comment by murillojorge** [comment]
I'm thinking about bottom alignment. 

![eoslocal-logo-dots-02](https://user-images.githubusercontent.com/1179619/48034806-6b4cc400-e126-11e8-994d-61d6bbe0aad1.png)

**Comment by gaboesquivel** [comment]
yes, I think it looks better
