### ISSUE TITLE
eosio/eos-dev deprecated ?

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/eos-local#27]
Now the `eosio.cdt` is the official way to compile smart contracts I'm wondering if the docker image `eosio/eos-dev` is also now deprecated along with the old `eosiocpp` command. 

We are still using `eosio/eos-dev` and installing `eosio.cdt` on top of it. 
Perhaps we should just be using `eosio/eos-dev`.

related to https://github.com/EOSIO/eos/issues/6242 

see https://github.com/eoscostarica/eos-local/blob/master/services/eos-dev/Dockerfile

**Comment by pakokrew** [comment]
The CDT is also published as an independent docker image 
https://hub.docker.com/r/eosio/cdt/

Instead of creating a docker image on top of eos-dev and installing cdt binary

**Comment by gaboesquivel** [comment]
thanks @pakokrew, I'll take a look.

**Comment by gaboesquivel** [comment]
closing in favor of https://github.com/eoscostarica/eos-local/issues/64
