### ISSUE TITLE
Add :: EOS Local Logo to the readme file

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/eos-local#30]
related to #23

**Comment by xavier506** [comment]
Here is another logo idea using a "loopback" concept from the loopback interface 127.0.0.01

thoughts?

![image 25](https://user-images.githubusercontent.com/5632966/48136073-56764a80-e264-11e8-9a9f-710b92b7f339.png)

**Comment by gaboesquivel** [comment]
@murillojorge I like it, thoughts ?

**Comment by edgar-eoscostarica** [comment]
I think it looks great but I'd like to get @murillojorge thoughts as well

**Comment by gaboesquivel** [comment]
This is the template we are going to use for the EOS Local website

http://demo.bonefishcode.com/wrapbootstrap/?item=flat_tech_html

Let's just make sure it plays well with it. that it doesn't look Alien, cos the theme is flat and this logo is not flat.

**Comment by gaboesquivel** [comment]
We want to use this version specifically http://demo.bonefishcode.com/flat-tech/demo/single-img/ 

In https://github.com/eoscostarica/eos-local/issues/23 @murillojorge explored a version that plays well with those colors 

@roafroaf

**Comment by edgar-eoscostarica** [comment]
In my opinion, the template shouldn't drive the design of the logo. Can we find a template that fits the logo proposed by @roafroaf ?

**Comment by gaboesquivel** [comment]
That works too.

**Comment by murillojorge** [comment]
Looks good. I'll update Zeplin.

**Comment by gaboesquivel** [comment]
cool tks!

**Comment by gaboesquivel** [comment]
Is there a white background version I can use in the readme file ?

**Comment by xavier506** [comment]
i havent seen one, can we use the ones we have now and change it later?
